version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: voting
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: voting
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password 
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"